import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import MainWrapper from "@/components/MainWrapper";

export const metadata: Metadata = {
  title: "Nawy Task",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainWrapper>{children}</MainWrapper>
        </Providers>
      </body>
    </html>
  );
}
